services:
  app:
    build: .
    image: tu-granja-image
    container_name: tu-granja-container
    volumes:
      - type: bind
        source: .
        target: /code
    ports:
      - 5001:5001
    stdin_open: true
    tty: true
    entrypoint: python app.py

  tu-granja-db:
    image: mysql:8.3.0
    container_name: tu-granja-db
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - tu-granja-db-volume:/var/lib/mysql
    ports:
      - $MYSQL_HOST_PORT:3306
    environment:
      MYSQL_ROOT_PASSWORD: tu-granja-root-password

volumes:
  tu-granja-db-volume:
    name: 'tu-granja-db-volume'